apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest

          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: socialrec

            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-cluster-kafka-bootstrap:9092

            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
              value: kafka-connect-cluster

            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
              value: http://kafka-connect-cluster-connect-api:8083

          ports:
            - containerPort: 8080