apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender

spec:
  replicas: 1

  selector:
    matchLabels:
      app: recommender

  template:
    metadata:
      labels:
        app: recommender

    spec:
      containers:
        - name: recommender
          image: recommender:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8001

          env:
            - name: CASSANDRA_HOST
              value: cassandra
            - name: CASSANDRA_PORT
              value: "9042"

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"