apiVersion: v1
kind: Secret
metadata:
  name: socialrec-ingestion-secrets
type: Opaque
stringData:
  batch-minio-root-user: minioadmin
  batch-minio-root-password: minioadmin
  batch-minio-bucket: socialrec-batch-raw
