apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-job
  labels:
    app.kubernetes.io/name: socialrec
    app.kubernetes.io/component: flink-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-job
  labels:
    app.kubernetes.io/name: socialrec
    app.kubernetes.io/component: flink-job
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - secrets
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-job
  labels:
    app.kubernetes.io/name: socialrec
    app.kubernetes.io/component: flink-job
subjects:
  - kind: ServiceAccount
    name: flink-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink-job
