apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-api

  template:
    metadata:
      labels:
        app: search-api

    spec:
      containers:
        - name: search-api
          image: search-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"

          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10