apiVersion: v1
kind: Secret
metadata:
  name: socialrec-secrets
type: Opaque
stringData:
  postgres-db: socialrec
  postgres-user: socialrec
  postgres-password: socialrec
  minio-root-user: minioadmin
  minio-root-password: minioadmin
  minio-bucket: socialrec-assets
  app-secret-key: dev-secret-key
