apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: init
          image: cassandra:4.1

          command: ["bash", "-c"]
          args:
            - |
              echo "Waiting for Cassandra..."

              until cqlsh cassandra 9042 -e "DESCRIBE KEYSPACES" >/dev/null 2>&1; do
                echo "Cassandra not ready..."
                sleep 5
              done

              echo "Running init script..."

              cqlsh cassandra 9042 -f /init/init.cql

          volumeMounts:
            - name: init-sql
              mountPath: /init

      volumes:
        - name: init-sql
          configMap:
            name: cassandra-init-sql