apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-sparkapplication-role
  namespace: socialrec
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "sparkapplications/status"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-sparkapplication-rolebinding
  namespace: socialrec
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: socialrec
  - kind: ServiceAccount
    name: airflow-scheduler
    namespace: socialrec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-sparkapplication-role