apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-star-schema-bi
  namespace: socialrec
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  # Tên image của bạn (khác với của bạn kia)
  image: socialrec-spark-star-schema:v1
  imagePullPolicy: IfNotPresent
  # Trỏ đúng vào file code của bạn
  mainApplicationFile: local:///opt/spark/app/star_schema_gold.py
  sparkVersion: 4.0.1
  restartPolicy:
    type: Never
  sparkConf:
    spark.hadoop.fs.s3a.endpoint: http://minio-batch:9000
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.sql.session.timeZone: UTC
  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark-operator-spark
    env:
      - name: MINIO_ENDPOINT
        value: http://minio-batch:9000
      - name: MINIO_ACCESS_KEY
        value: minioadmin
      - name: MINIO_SECRET_KEY
        value: minioadmin
      - name: MINIO_BUCKET
        value: socialrec-batch
      - name: SILVER_PREFIX
        value: silver
      - name: GOLD_PREFIX
        value: gold_bi
  executor:
    instances: 2
    cores: 1
    memory: 1g